version: '3.9'
services:
  front:
    build:
      dockerfile: ./apps/front/Dockerfile
      target: development
      context: .
    command: npm run serve:front
    expose:
      - 4200
    ports:
      - '4200:4200'
    depends_on:
      - express
    volumes:
      - .:/app
      - /app/node_modules
  express:
    build:
      dockerfile: ./apps/express/Dockerfile
      target: development
      context: .
    command: npm run serve:express
    expose:
      - 4000
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5010
      DATABASE_USER: root
      DATABASE_NAME: root
      DATABASE_PASSWORD: root
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    volumes:
      - ./docker-postgres-multiple-dbs.sh:/docker-entrypoint-initdb.d/docker-postgres-multiple-dbs.sh
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB_NAMES: chatbot

networks:
  default:
    name: example_dev_network
    driver: bridge
